version: '3.9'

services:
  fastapi:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - 8000:80
    depends_on:
      - db
  
  db:
    container_name: postgres
    image: postgres:12
    restart: "always"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:latest"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
    
volumes:
  postgres_data:      